name = "openai-api-worker"
main = "openai-api-worker.js"
compatibility_date = "2025-05-31"

[env.production.vars]
# Your environment variables will be set here
# OPENAI_API_KEY will need to be set via wrangler secret put OPENAI_API_KEY
